### ISSUE TITLE
プログラムに必要な機能

### ISSUE THREAD

**Issue by nkm071** [rdc-autonomous-mobile-robot-project/box_chaser#5]
waypoint_manegerとの統合のために必要なこと

- [x] finishクライアント
宅配ボックス（青い箱）を認識した時にコールする
detect_resultクライアント

手順の一番最後の時かつ箱を認識したかどうかの時にTrue or Falseでコールする

- [x] label_stringパブリッシャー
tag_aのようなタグの種類をパブリッシュする
一回だけが望ましい（空文字がパブリッシュされるとエリアに行かない）

- [x] detect_resultクライアント
スキップウェイポイントをするためのクライアント？

- [x] detect_boxサーバー
ストップウェイポイントに到達した時にコールされるサーバー
このコールをもってnav_simとfilterが動作し始める

動作確認済みのものにチェックをつける

**Comment by hellocit** [comment]
detect_boxは実装済み

**Comment by nkm071** [comment]
finishクライアントに関してタイミングがあっているか未確認だがサーバーが応答していることを確認

**Comment by nkm071** [comment]
detect_resultについてはタイミングがあっていない．

**Comment by nkm071** [comment]
label_stringについて動作していることを確認．タイミングは未検証

**Comment by nkm071** [comment]
area_selectについては上記で良さそう

**Comment by nkm071** [comment]
detect_resultについて
https://github.com/rdc-autonomous-mobile-robot-project/box_chaser/issues/9

**Comment by nkm071** [comment]
すべての機能について実装できた．issueを閉じる．
